"""add takin add user_id to apps

Revision ID: e30114cde917
Revises: cf8f4fc45278
Create Date: 2025-01-23 12:01:50.049769

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30114cde917'
down_revision = 'cf8f4fc45278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', models.types.StringUUID(), nullable=False))

    with op.batch_alter_table('tool_api_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish', sa.Boolean(), nullable=True))

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('outputs',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('outputs',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('tool_api_providers', schema=None) as batch_op:
        batch_op.drop_column('publish')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
